In [1]:
import pandas as pd
import numpy as np
import re
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score
from sklearn.feature_extraction.text import TfidfVectorizer



In [5]:
df = pd.read_csv('sentimen_kalimat.csv')
df


kalimat  status
0     eh ihh uhh ehh uhh ohh eeh uhhh oooh uuh ahhh ...       0
1     iiih aah uhh ohhh eh aaah ehh ehh uuuh ihh ihh...       2
2                      ooh uhhh aah ah ah iiih ohh oooh       1
3     ohh ahh ahhh aah oooh ihhh oooh ohhh oooh ohhh...       0
4                                   aah ih ehhh eeh ahh       2
...                                                 ...     ...
4995                          uhhh ooh uhhh uuuh uh uhh       0
4996                         eh ohhh aaah uh uuuh uh eh       0
4997  ih uhhh ahh ihh ohh ihhh aah ihh uuuh ih uhh i...       2
4998  eeh ahhh iih ooh uhhh eeh uh ohh eeh eeh uuuh ...       0
4999                    ehh ohh iih ooh ehh uuh oooh oh       0

[5000 rows x 2 columns]

In [6]:
x = df.values[:,0]
y = df.values[:,1].astype(int)

In [7]:
otak = TfidfVectorizer()
otak.fit(x)
x = otak.transform(x).toarray()

In [8]:
batas = df.values.shape[0] * 8//10
x_train = x[ : batas]
y_train = y[ : batas]
x_test = x[batas : ]
y_test = y[batas : ]

In [9]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(4000, 25)
(4000,)
(1000, 25)
(1000,)


In [10]:
print(x_train)
print(y_train)

[[0.         0.32295303 0.163146   ... 0.16271609 0.16209427 0.        ]
 [0.12977961 0.39221829 0.         ... 0.13174305 0.         0.26104328]
 [0.         0.31380187 0.63409243 ... 0.31621078 0.         0.        ]
 ...
 [0.49282453 0.         0.25080113 ... 0.25014025 0.12459216 0.12391058]
 [0.         0.14844028 0.44992494 ... 0.         0.14900816 0.148193  ]
 [0.         0.34615994 0.         ... 0.         0.17374211 0.        ]]
[0 2 1 ... 0 0 2]


In [11]:
from sklearn.ensemble import ExtraTreesClassifier
etc = ExtraTreesClassifier()
etc.fit(x_train, y_train)

ExtraTreesClassifier()

In [98]:
from sklearn.metrics import silhouette_score
score = silhouette_score(x_train, y_train_pred)
print("akurasi = ",score)

akurasi =  0.016922155922437815


In [99]:
df = df.values[:,0]
df = [_.split() for _ in df]

In [104]:
from gensim.models import Word2Vec
otak = Word2Vec(df)
print(otak.wv['ah'])
print(otak.wv['ih'])

[-0.02470556  0.1477152   0.14141728  0.10763969 -0.0107321  -0.11465689
  0.09924944  0.2705811  -0.13803966 -0.25375327  0.03620116 -0.18048006
  0.07606372  0.06595987  0.12262124 -0.00775258  0.20601258  0.02557022
 -0.04768884 -0.33631778  0.07098029  0.04608604  0.09137752 -0.02113618
 -0.1699178   0.16245963 -0.14641564  0.03316449  0.05158402  0.01291499
  0.1721126  -0.1292591  -0.0161036  -0.1196059  -0.07227106  0.09840617
  0.12679237 -0.00120505 -0.18031916  0.01147303  0.22911757 -0.08932149
 -0.00803185  0.1609892   0.07956515 -0.12608875 -0.14849462 -0.20892395
  0.06258558  0.02067215  0.11967237 -0.1292959  -0.04720788 -0.02829929
 -0.14432487  0.07894487  0.10612488 -0.00260698  0.08580537 -0.03152208
 -0.08419611 -0.03436856  0.25326514  0.12770084 -0.09065917  0.27892005
 -0.026576    0.12699814 -0.12691759  0.0200493   0.00801865  0.16025971
  0.09019582  0.08032432  0.15583788  0.07905493  0.16533661  0.15974703
 -0.03997704 -0.01951287 -0.26919317 -0.04552431  0

In [101]:
!pip install gensim

     -------------------------------------- 23.9/23.9 MB 440.0 kB/s eta 0:00:00
     ------------------------------------ 983.8/983.8 kB 494.4 kB/s eta 0:00:00
     -------------------------------------- 58.6/58.6 kB 612.4 kB/s eta 0:00:00


In [108]:
otak.wv.most_similar('ah')

[('ohhh', 0.9982208609580994),
 ('ahh', 0.9981349110603333),
 ('ohh', 0.9979767203330994),
 ('eeh', 0.9979012608528137),
 ('ehhh', 0.997793436050415),
 ('iih', 0.9976956844329834),
 ('uhh', 0.9976951479911804),
 ('eh', 0.9976390600204468),
 ('ihh', 0.9975813627243042),
 ('uuh', 0.9975090622901917)]